## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
notifications:
  email: false

# Do not build branches
# * https://docs.travis-ci.com/user/conditional-builds-stages-jobs
# * https://docs.travis-ci.com/user/conditions-v1
if: branch = master OR tag IS present OR type != push
