## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false

# Do not build branches
# * https://docs.travis-ci.com/user/conditional-builds-stages-jobs
# * https://docs.travis-ci.com/user/conditions-v1
if: branch = master OR tag IS present OR type != push

script:
  - julia -e 'using Pkg; pkg"add MbedTLS"'
  - head -n20 /home/travis/.julia/packages/MbedTLS/X4xar/src/MbedTLS.jl
  - julia -e 'using MbedTLS'
